### ISSUE TITLE
How to retrieve results with keywords any where in a field ?!

### ISSUE THREAD

**Issue by acrolink** [maxivak/bootstrap3_autocomplete_input#14]
I mean, the current setup returns results that start with a keyword. I wonder, how to obtain results that contain all entered keywords with no regard to order in DB field? Thank you 👍

**Comment by maxivak** [comment]
see example:
https://github.com/maxivak/bootstrap3_autocomplete_input/wiki/Full-field-search

```
    autocomplete :users, :name, { full: true }
```
