### ISSUE TITLE
How to use where condition?

### ISSUE THREAD

**Issue by mbackermann** [maxivak/bootstrap3_autocomplete_input#15]
I have a user model that is working fine, but I can't use the where condition properly. I need to list all the users from the same company as the user that is searching. I have a field in user model called company_id, so I want only to search the users that has the same company_id. How can I do it?

**Comment by dkru** [comment]
Hi. I have a same problem, how you diside?

**Comment by mbackermann** [comment]
Hi @dkru,

I abandoned this Gem and created the solution myself.

**Comment by dkru** [comment]
You are not documented your solution? If you documented, please give me a
link. :)

**Comment by maxivak** [comment]
i added an example:
https://github.com/maxivak/bootstrap3_autocomplete_input/wiki/search-where

```
autocomplete :user, :name, { :where => 'company_id=1' }
```

**Comment by dkru** [comment]
Thank you Max for you reply. but i have another question. How i send condition WHERE if i use a variable, execute's WHERE with different value's. In controller this option is not compatible. From simple form input condition WHERE is doesnt work.
simple example: :where => 'company_id = '+params[:company_id]

**Comment by maxivak** [comment]
option 1.
if you want full control over data you get for your input - you can write your custom controller method.
see example
https://github.com/maxivak/bootstrap3_autocomplete_input/wiki/search-custom-method

option 2.
dynamic where condition
:where => (proc here)

I am working on adding dynamic conditions for where.

**Comment by dkru** [comment]
Tnak you. At this time i use option 1, and wait for you develop this
function. Thank you for you work!!!
I' ready for help, if it requre.

2017-05-11 13:41 GMT+03:00 Max Ivak <notifications@github.com>:

**Comment by maxivak** [comment]
In new version of gem '0.2.1' you can use :where_method option to create dynamic search conditions.
```
  autocomplete :client, :name, { :where_method => :w_region }
```

see example:
https://github.com/maxivak/bootstrap3_autocomplete_input/wiki/search-where
