### ISSUE TITLE
Modify value of hidden field

### ISSUE THREAD

**Issue by glafir** [maxivak/bootstrap3_autocomplete_input#17]
Hello!
How can I modify value of hidden field in autocomplete-feald?
For example simple autocomplete field
```
= f.input :aircompany, :as => :autocomplete, :source_query => autoco
mplete_aircompany_airline_name_rus_aircompanies_path
```

This ganarate HTML
`<div class="form-group autocomplete optional timetableap_aircompany"><label class="control-label autocomplete optional" for="timetableap_aircompany">Aircompany</label><input id="timetableap_aircompany_id" value="" required="required" type="hidden" name="timetableap[aircompany_id]" /><input class="form-control autocomplete optional" data-provide="typeahead" autocomplete="off" data-source-query="/aircompanies/autocomplete_aircompany_airline_name_rus" data-items="8" data-min-length="1" data-afterSelect="false" data-field-id="timetableap_aircompany_id" type="text" value="" name="timetableap[aircompany]" id="timetableap_aircompany" /></div>`
How can I change value of hidden field?
`input id="timetableap_aircompany_id" value="<SOMETHING_CHANGE_PARAMS>" required="required" type="hidden" name="timetableap[aircompany_id]" />`

**Comment by maxivak** [comment]
by default, the ID hidden field should have the value from your model from field aircompany_id.

you can set value for ID explicitly with :value option:
```
= f.input :aircompany, :as => :autocomplete, :source_query => autoco
mplete_aircompany_airline_name_rus_aircompanies_path, :value => YOUR_VALUE

```

**Comment by webdev-rc** [comment]
Oh, Yes! Thank you!
But May I set only hidden value and visible input singly?

**Comment by glafir** [comment]
Oh, Yes! Thank you!
But May I set only hidden value and visible input singly?
