### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by saileereddy** [maxivak/bootstrap3_autocomplete_input#4]
Hi,

I have added gem and also included required files for autocomplete.

But my column name is different so added configuration as -

```
autocomplete :event_type, :event_type_name, ({ column_name: 'event_type_name' })

```

And I am getting response in logs but while displaying getting javascript error as of undefined read property name.

Can you please suggest if any configuration need to done.

**Comment by maxivak** [comment]
Try this:

{ :column_name=>'event_type_name', :display_value => 'fullname', :full_model=>true }

It will search by column 'event_type_name' and display another column 'fullname'.
Option :full_model is important becayse :display_value is different column than :column_name.

**Comment by saileereddy** [comment]
Still I am getting same, not sure what is the exact issue

```
autocomplete :event_type, :name, ({ column_name: 'event_type_name', display_value: 'occasion_name', full_model: true })

```

Added this in controller and in model

```
  def occasion_name
    event_type_name
  end
```

In view

```
<%= f.input :event_type, as: :autocomplete, source_query:autocomplete_event_type_name_events_path %>
```

In bootstrap-typehead.min.js I am getting error -

```
displayText:function(a){return a.name||a}

```

**Comment by maxivak** [comment]
If you have event_type_name column in the model and you search in this column and want to display this column, then you can define as:

```
 autocomplete :event_type, :event_type_name
```

Do you define this in EventsController ?

How is your route defined in routes.rb ?

What is the response from the server? It should be data in JSON format. 
Like this

```
[["2","Banana"]]
```

If the response is ok, then it may be an issue with jquery.
I recommend using jquery2 (not jquery) in assets ('app/assets/javascripts/application.js'):

``` bash
//= require jquery2
//= require jquery_ujs
//= require bootstrap
//= require bootstrap3-typeahead.min
//= require bootstrap3-autocomplete-input.min

```

**Comment by maxivak** [comment]
Notice that it should be :event_type_name, not :name, if your column in database is 'event_type_name':

```
 autocomplete :event_type, :event_type_name
```

What's the column name ? event_type_name, type_name or name ?

**Comment by saileereddy** [comment]
Yes, I have tried with column name as event_type_name

```
 autocomplete :event_type, :event_type_name
```

but still same issue

**Comment by saileereddy** [comment]
Please find the details of controller, model and view

Events Controller -

```
autocomplete :event_type, :event_type_name, ({ column_name: 'event_type_name', display_value: 'occasion_name', full_model: true })
```

event_type.rb model

```
def occasion_name
    event_type_name
  end
```

routes

```
get 'autocomplete_event_type_event_type_name'
```

view

```
<%= f.input :event_type, as: :autocomplete, source_query:autocomplete_event_type_event_type_name_events_path %>
```

**Comment by saileereddy** [comment]
When I updated the jquery, I am getting the error as -

```
Uncaught TypeError: b.toLowerCase is not a function
```

**Comment by maxivak** [comment]
Usually routes can be specified inside resources block :

``` ruby
  resources :clients do
    get :autocomplete_client_name, :on => :collection
  end
```

in your case :

``` ruby
resources :event_types do
    get :autocomplete_event_type_name, :on => :collection
end
```

I am not sure what you get when have only 'get 'autocomplete_event_type_event_type_name'.

run `rake routes` and show the output of your routes.

**Comment by saileereddy** [comment]
I have added like this - 

```
resources :events do
   collection do
      get 'autocomplete_event_type_event_type_name'
    end
end
```

rake routes output

```
autocomplete_event_type_event_type_name_events GET      /events/autocomplete_event_type_event_type_name(.:format) events#autocomplete_event_type_event_type_name
```

**Comment by maxivak** [comment]
In order to make it straightforward it is better to place autocomplete in the controller devoted to the model you are searching in. Old examples in the gem did it differently.

Step-by-step:

Models:

``` ruby
Event
   has_many :event_types

EventType
  belongs_to :event

  # has column :event_type_name
```

Controllers:

``` ruby
class EventTypesController < ApplicationController
  autocomplete :event_type, :event_type_name


```

note that autocomplete is placed in EventTypesController, not in EventsController.

routes:

``` ruby
resources :event_types do
    get :autocomplete_event_type_name, :on => :collection
end
```

check routes running

``` ruby
rake routes
```

the output should have

``` ruby
autocomplete_event_type_event_type_name_event_types GET    /event_types/autocomplete_event_type_event_type_name(.:format) event_types#autocomplete_event_type_event_type_name      
```

View:

``` ruby
<%= f.input :event_type, as: :autocomplete, source_query:autocomplete_event_type_event_type_name_event_types_path %>
```

**Comment by maxivak** [comment]
Routes looks fine.

Could you show logs what it invokes after you start typing in the field:
Should be smth like this:

``` ruby

Started GET "/clients/autocomplete_client_name?q=a" for 127.0.0.1 at 2015-07-1417:49:31 +0300
Processing by ClientsController#autocomplete_client_name as JSON
  Parameters: {"q"=>"a"}
  Client Load (26.0ms)  SELECT  clients.id, clients.name FROM "clients" WHERE (LOWER(clients.name) LIKE 'a%')  ORDER BY clients.name ASC LIMIT 10
Completed 200 OK in 31ms (Views: 0.0ms | ActiveRecord: 26.0ms)

```

**Comment by maxivak** [comment]
Try to open URL in browser 

/events/autocomplete_event_type_event_type_name?q=__some_string_here

what does it return ?

It should be text with JSON data.

I suspect it returns empty strings like

[[5,], [7,]]

while it should be
[[5,'name1'],[7,'name2']]

**Comment by saileereddy** [comment]
please find the logs -

```
Started GET "/events/autocomplete_event_type_name?q=a" for 127.0.0.1 at 2015-07-14 23:50:29 +0530
Processing by EventsController#autocomplete_event_type_name as JSON
  Parameters: {"q"=>"a"}
  User Load (1.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", "9369ab01-afb9-4abf-b310-6bf419ff7652"]]
  EventType Load (27.1ms)  SELECT  "event_types".* FROM "event_types" WHERE "event_types"."deleted_at" IS NULL AND (LOWER(event_types.event_type_name) ILIKE 'a%')  ORDER BY event_types.event_type_name ASC LIMIT 10
```

Output in browser -

```
{"events":[["b11fd919-2837-422a-a2c9-917e1bee2720","Anniversary"],["1998c861-d020-4e07-8234-5d66c34a094b","Anniversary"]]}
```

**Comment by maxivak** [comment]
That's wierd. 
Because it should be array of arrays, not hash.

```
[["b11fd919-2837-422a-a2c9-917e1bee2720","Anniversary"],["1998c861-d020-4e07-8234-5d66c34a094b","Anniversary"]]
```

to check if javascript works fine try this in your controller:

``` ruby
class EventsController < ...
  # comment autocomplete
  #autocomplete :event_type, :event_type_name

# define the method itself
   def autocomplete_event_type_name
       a = [["b11fd919-2837-422a-a2c9-917e1bee2720","Anniversary"],["1998c861-d020-4e07-8234-5d66c34a094b","Anniversary"]]

render :json => a
   end


```

see if it shows list in autocomplete field in form.

**Comment by maxivak** [comment]
Also check the version of the gem.
It should be '0.1.7'

**Comment by saileereddy** [comment]
Still same issue -

```
Uncaught TypeError: b.toLowerCase is not a function
```

**Comment by saileereddy** [comment]
Yes, version of gem is - 0.1.7

```
bootstrap3_autocomplete_input-0.1.7

```

**Comment by maxivak** [comment]
Then it looks like an issue with javascript.
Having this in application.js

``` ruby
//= require jquery2
//= require jquery_ujs
//= require bootstrap
//= require bootstrap3-typeahead
//= require bootstrap3-autocomplete-input.min

```

Check the version of bootstrap-sass gem and jquery related gems.
I have:

``` ruby
jquery-rails (4.0.4) 
jquery-ui-rails (5.0.5)
bootstrap-sass (3.3.5.1)
```

I am using     `bootstrap-sass (3.3.5.1)` that includes bootstrap v3.3.5.

Open `http://localhost:3000/assets/bootstrap.self.js?body=1` in browser.

```
/*!
 * Bootstrap v3.3.5 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under the MIT license
 */
```

**Comment by maxivak** [comment]
Please show the generated HTML for the autocomplete field.

**Comment by saileereddy** [comment]
Generated html

```
<div class="form-group autocomplete optional event_event_type">
<label class="autocomplete optional control-label" for="event_event_type">Event type</label>
<input id="event_event_type_id" type="hidden" name="event[event_type_id]">
<input class="autocomplete optional form-control" data-provide="typeahead" autocomplete="off" data-source-query="http://localhost:3000/events/autocomplete_event_type_event_type_name" data-items="8" data-min-length="1" data-afterselect="false" data-field-id="event_event_type_id" type="text" name="event[event_type]" id="event_event_type">
</div>
```

**Comment by saileereddy** [comment]
```jquery-rails-4.0.3

**Comment by saileereddy** [comment]
```
jquery-rails-4.0.3
bootstrap-sass-3.3.4.1
```

**Comment by maxivak** [comment]
Please show again the logs for opening the URL `http://localhost:3000/events/autocomplete_event_type_event_type_name?q=a' and output in browser.

Before you showed different URL `Started GET "/events/autocomplete_event_type_name?q=a" ..`.
Please show the new one which you have in HTML.

**Comment by saileereddy** [comment]
URL -

```
Started GET "/events/autocomplete_event_type_event_type_name?q=a" for 127.0.0.1 at 2015-07-15 00:47:21 +0530
Processing by EventsController#autocomplete_event_type_event_type_name as JSON
  Parameters: {"q"=>"a"}
  User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", "9369ab01-afb9-4abf-b310-6bf419ff7652"]]
Completed 200 OK in 24ms (Views: 20.4ms | ActiveRecord: 0.7ms)
```

**Comment by saileereddy** [comment]
When I hit in browser it output -

```
{"events":[["b11fd919-2837-422a-a2c9-917e1bee2720","Anniversary"],["1998c861-d020-4e07-8234-5d66c34a094b","Anniversary"]]}

```

**Comment by maxivak** [comment]
It shows data in wrong format..

when I have this in me method:

``` ruby

  def autocomplete_client_name
    a = {:events => [["b11fd919-2837-422a-a2c9-917e1bee2720","Anniversary"],["1998c861-d020-4e07-8234-5d66c34a094b","Anniversary"]] }
    render :json => a
  end


```

it shows the same error :

``` ruby
TypeError: it.toLowerCase is not a function
return ~it.toLowerCase().indexOf(this.query.toLowerCase());
```

Try this in your controller:

``` ruby
class EventsController < ApplicationController
  # remove this line
   # autocomplete ...

    # add this method

def autocomplete_event_type_event_type_name
    a = [["b11fd919-2837-422a-a2c9-917e1bee2720","Anniversary"],["1998c861-d020-4e07-8234-5d66c34a094b","Anniversary"]]
    render :json => a
end


```

Could you send me an archive with your project and database so I can check it with your gems.

**Comment by saileereddy** [comment]
I have added same method with data but render json: a is adding up events -

```
def autocomplete_event_type_event_type_name
     a = [['b11fd919-2837-422a-a2c9-917e1bee2720', 'Anniversary'], ['1998c861-d020-4e07-8234-5d66c34a094b', 'Anniversary']]
    render json: a
end

[1] pry(#<EventsController>)> render json: a
=> ["{\"events\":[[\"b11fd919-2837-422a-a2c9-917e1bee2720\",\"Anniversary\"],[\"1998c861-d020-4e07-8234-5d66c34a094b\",\"Anniversary\"]]}"]
```

**Comment by maxivak** [comment]
Do you have gems which work with json?
Do you have filters/callbacks in your controller or ApplicationController ?

**Comment by saileereddy** [comment]
No, I am not having gem related to json and also callbacks are not present

**Comment by maxivak** [comment]
Double check your controller.
Also add '.to_json'

``` ruby
  def autocomplete_client_name
    a = [["123","First"],["456","Second"], ["3", "Third"]]
    render :json => a.to_json
  end
```

It shouldn't add 'events' to hash.

**Comment by saileereddy** [comment]
I am using serializer gem - https://github.com/jrhe/grape-active_model_serializers

**Comment by saileereddy** [comment]
Thanks 
This method works -

```
def autocomplete_client_name
    a = [["123","First"],["456","Second"], ["3", "Third"]]
    render :json => a.to_json
  end
```

**Comment by maxivak** [comment]
Oh!

It could be an issue.

According to the gem

```

  # All standard options for `ActiveModel::Serializers` are supported.
  get "/fancy_homes", root: 'world', each_serializer: FancyHomesSerializer
```

try to specify no serializer for your route. 
Or when returning data specify 'return json: a, serializer: false' or something.

Not sure how to do it for that gem.

**Comment by saileereddy** [comment]
Okay, thanks.

**Comment by maxivak** [comment]
Let me fix this in my gem to call `.to_json`.
It will be in a new version soon.

Thanks!

**Comment by saileereddy** [comment]
:+1:

**Comment by maxivak** [comment]
Please, use a new version '0.1.8'.
Let me now if it works.

**Comment by saileereddy** [comment]
okay

**Comment by saileereddy** [comment]
Thanks, working properly with new version.
