### ISSUE TITLE
Strange behavior on Safari

### ISSUE THREAD

**Issue by tacionery** [maxivak/bootstrap3_autocomplete_input#7]
Hey guys,
When I open the page with the autocomplete input on Safari, it doesn't work at first time. I have to reload the page to get it working...

**Comment by maxivak** [comment]
If you are using turbolinks then review this [issue](https://github.com/maxivak/bootstrap3_autocomplete_input/issues/5).
The solution for using the gem with turbolinks - https://github.com/maxivak/bootstrap3_autocomplete_input/wiki/turbolinks

**Comment by tacionery** [comment]
Thanks friend! It works perfectly now!
