### ISSUE TITLE
Turbolinks support

### ISSUE THREAD

**Issue by wynksaiddestroy** [maxivak/bootstrap3_autocomplete_input#8]
If I'm not mistaken bootstrap3_autocomplete_input relies on jQuerys `$(document).ready()` method. Therefore the gem doesn't work well with turbolinks aside from using [jquery.turbolinks](https://github.com/kossnocorp/jquery.turbolinks) for example. Are you going to support turbolinks in the near future?

Thanks in advance

**Comment by maxivak** [comment]
see this issue https://github.com/maxivak/bootstrap3_autocomplete_input/issues/5.
